# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bb8dcc9dec32105fb59bfba507b089bffb4d78be6637017e964ee6553979824c83a0e4201091669f6edd2ea05b994f78aadcff1a6ed080febfdd2e64fe87db5

test:
  secret_key_base: 2e4e07a4aeb65d2f50be901a15450ae39dc0bad4df6616fc94733b9cefc5a1b74ff35ae6e2e21394191c4b9216919319d4b02ca685076fb92e2f698f2837ce97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
